export { default as Banner } from "./Banner/Banner";
export { default as Brands } from "./Brands/Brands";
export { default as Benefits } from "./Benefits/Benefits";
export { default as Hero } from "./Hero/Hero";
export { default as OurNumbers } from "./OurNumbers/OurNumbers";
export { default as Blog } from "./Blog/Blog";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as Footer } from "./Footer/Footer";
export { default as Mail } from "./Mail/Mail";
